name: Deploy Production
on: { push: { branches: [ production ] } }
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: node_modules-
    - uses: actions/setup-node@v1
      with: { node-version: '12' }
    - run: yarn --frozen-lockfile

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - uses: actions/setup-node@v1
        with: { node-version: '12' }
      - run: yarn deploy:production
    